
version: '2'
services:
  ##### the develop image you've build
  ### don't forget to open ports for your app
  dev-image:
    image: conan-clang-cmake
    ports:
      - "2000:2000"
      - "50010:50010"
    privileged: true
    container_name: devenv
# mapping your project folder (.) to /home/develop/project    
    volumes:
      - "${PWD}:/home/develop/src"
      - "/mnt/build:/home/develop/build:rw"