version: '3.5'
services:
  dev-image:
    image: conan-gcc10-cmake-gdb
    ports:
      - "2000:2000"
      - "50010:50010"
    privileged: true
    tty: true
    container_name: devenv
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - "${HOST_SRC_FOLDER}:/mnt/src:rw"
      - "${HOST_BUILD_FOLDER}:/mnt/build:rw"
      - "${HOST_CONAN_FOLDER}/data:/root/.conan/data:rw"
    working_dir: /mnt/build
